### ISSUE TITLE
evaluation metrics 

### ISSUE THREAD

**Issue by arjunpuri7** [gykovacs/smote_variants#15]
I want to calculate true positive and true negative in my model and trying to use sklearn.metrics using some techniques mentioned in smote_variants.
how can I uses these metrics with smote_variants? if not can you provide true positive, true negative rate in your module?

from, 
Arjun Puri

**Comment by arjunpuri7** [comment]
I use code 'Integration with sklearn' but error appear:

module 'smote_variants' has no attribute 'OversamplingClassifier' 

I update library but still not working. please help me out

**Comment by gykovacs** [comment]
Could you please provide the details of your system and also a minimal sample code which is not working?

**Comment by arjunpuri7** [comment]
windows 8.1 
version of python: 3.6.4


code 
import smote_variants as sv
import imblearn.datasets as imb_datasets

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

libras= imb_datasets.fetch_datasets()['libras_move']
X, y= libras['data'], libras['target']

oversampler= sv.MulticlassOversampling(sv.distance_SMOTE())
classifier= KNeighborsClassifier(n_neighbors= 5)

# Constructing a pipeline which contains oversampling and classification as the last step.
model= Pipeline([('scale', StandardScaler()), ('clf', sv.OversamplingClassifier(oversampler, classifier))])

model.fit(X, y)

**Comment by gykovacs** [comment]
This is definitely a working sample code. What does

sv.__version__

give?

**Comment by gykovacs** [comment]
Sorry, github formatted the text, as a code:
```
sv.__version__
```

**Comment by arjunpuri7** [comment]
smote_variants : 0.3.4

**Comment by arjunpuri7** [comment]
now its working thanks...
