### ISSUE TITLE
AttributeError: module 'smote_variants' has no attribute 'Borderline_SMOTE1'

### ISSUE THREAD

**Issue by junmeiW** [gykovacs/smote_variants#3]
Hi,
recently I'm learning the SMOTE related methods, and I installed the smote_variants package by pip, and there was no error when installing.

But it showed the attribute error when I tried to use the SMOTE and Borderline_SMOTE methods.
Could you please help me for this problem?

Thank you very much!

**Comment by gykovacs** [comment]
Sure! Could you please share the piece of code you tried to execute?

**Comment by junmeiW** [comment]
Yeah!
Thank you very much.

I upload the zip file (including my code and file). Please check it!

[smote_py.zip](https://github.com/gykovacs/smote_variants/files/3259709/smote_py.zip)

Thanks again!

**Comment by gykovacs** [comment]
What Python version are you using?

**Comment by junmeiW** [comment]
My Python version is 3.6.5

**Comment by gykovacs** [comment]
One last question: Windows/Linux or MacOS?

**Comment by junmeiW** [comment]
Windows10.

**Comment by gykovacs** [comment]
Hi @junmeiW,

I tried your notebook on a Win10 box, with Python 3.6.5 and works fine, apart from the fact that the ```sample``` function does take ```numpy``` arrays with no ```NaN```s, thus,

```
X_train= X_train.fillna(0)
oversampler= xv.SMOTE(proportion=0.1, n_jobs=2)
X_samp, y_samp= oversampler.sample(X_train.values, y_train.values)
```
works fine.

Put in another way, I could not reproduce the problem you face. What Python distribution are you using, pure Python, Miniconda or Anaconda? I tried in Anaconda. The error is very strange, seemingly the ```smote_variants``` package can be imported in your environment but the fields are not available. Could you please also run ```dir(sv)``` and copy here the output?

**Comment by junmeiW** [comment]
So sorry reply late.

I run python code  using Anaconda. and run ```dir(sv)```(smote_variants)
I got `
['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__']
`

**Comment by gykovacs** [comment]
Seemingly there is something wrong with your install, there should be lots of other variable names defined in sv. Unfortunately I could not reproduce it. Could you please give it a try in a separate, new virtual environment?
