### ISSUE TITLE
I want to use in my dataset to apply smote variants but is not working 

### ISSUE THREAD

**Issue by arjunpuri7** [gykovacs/smote_variants#6]

**Comment by arjunpuri7** [comment]
I want to use evaluate_oversampler method on my datasets and perform following steps:
import smote_variants as sv
import pandas as pd
import numpy as np
data=pd.read_csv(".........original/glass0.csv")
x=data.drop('10',axis=1)
X=x.as_matrix()
y=data.iloc[:,-1]
Y=y.as_matrix()
datasets={'data':X,'target':Y,'name':'glass0'}
print(datasets)
oversamplers= [sv.SMOTE_ENN, sv.NEATER, sv.Lee]
classifiers= [KNeighborsClassifier(n_neighbors= 3),
              KNeighborsClassifier(n_neighbors= 5),
              DecisionTreeClassifier()]
cache_path= 'C:/Users/hp/Desktop/python codes/structure'

results= sv.evaluate_oversamplers(datasets,
                               oversamplers,
                               classifiers,
                               cache_path)

after applying all this i get an error;

![error](https://user-images.githubusercontent.com/35588369/60772024-0afb9100-a0be-11e9-9b08-047483f0e728.png)

**Comment by gykovacs** [comment]
Hi @arjunpuri7, the ```evaluate_oversamplers``` function takes a list of datasets to evaluate on, therefore, all you need to do is put the dataset specification in a list as

```
datasets=[{'data':X,'target':Y,'name':'glass0'}]
```
Let me know if it works!

**Comment by arjunpuri7** [comment]
i try and it works thanks
